### ISSUE TITLE
Pls asaign me this task i will make your website responsive for mobile,tablet and laptop

### ISSUE THREAD

**Issue by kishanlalchoudhary** [Suvradippaul/Responsive-web-design#7]

**Comment by Suvradippaul** [comment]
Hey @kishanlalchoudhary, go ahead 🚀

**Comment by kishanlalchoudhary** [comment]
Okay I will do it I it ok if I change some things in ui

**Comment by kishanlalchoudhary** [comment]
can you confirm one thing are you mainter in hactoberfest

**Comment by Suvradippaul** [comment]
> can you confirm one thing are you mainter in hactoberfest

Yes, for this repo. You can be as well. Build projects, tell everyone what the project is about and how it can be improved in form of contributions/collaborations. 
Open Source Communities are always there to help you.

**Comment by Suvradippaul** [comment]
> Okay I will do it I it ok if I change some things in ui

No issues, feel free to do so 👍
Let me know if you need any help.

**Comment by kishanlalchoudhary** [comment]
okay

**Comment by kishanlalchoudhary** [comment]
then i will make this website totally responsive then you can merge it

**Comment by kishanlalchoudhary** [comment]
i have made responsive pls accept my pr
